python/0255 - HyperSchool/task/HyperSchool/urls.py
from django.contrib import admin
from django.urls import path, include

from schedule.views import SignUpView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('schedule/', include('schedule.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

python/0255 - HyperSchool/task/schedule/urls.py
from django.urls import path

from .views import CourseDetailView, EnrollView, MainView, TeacherDetailView

urlpatterns = [
    path('main/', MainView.as_view(), name='main'),
    path('course_details/<int:pk>', CourseDetailView.as_view(), name='course_details'),
    path('teacher_details/<int:pk>', TeacherDetailView.as_view(), name='teacher_details'),
    path('add_course/', EnrollView.as_view(), name='enroll'),
]

python/0255 - HyperSchool/task/schedule/models.py
from django.db import models


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    age = models.IntegerField()
    about = models.TextField()

    def __str__(self):
        return f'{self.name} {self.surname}'


class Course(models.Model):
    title = models.CharField(max_length=255)
    info = models.TextField()
    duration_months = models.IntegerField()
    price = models.DecimalField(max_digits=1000, decimal_places=2)
    teacher = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField()
    course = models.ManyToManyField(Course)

    def __str__(self):
        return f'{self.name} {self.surname}'

python/0255 - HyperSchool/task/schedule/forms.py
from django import forms

from .models import Student


class SearchForm(forms.Form):
    q = forms.CharField()


class EnrollForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'age', 'course']

python/0255 - HyperSchool/task/schedule/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, FormView

from .forms import EnrollForm, SearchForm
from .models import Course, Teacher


class MainView(ListView):
    model = Course
    template_name = 'schedule/main.html'
    context_object_name = 'courses'

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data['q']
            return Course.objects.filter(title__icontains=query)
        return Course.objects.all()


class CourseDetailView(DetailView):
    model = Course
    template_name = 'schedule/course_details.html'


class TeacherDetailView(DetailView):
    model = Teacher
    template_name = 'schedule/teacher_details.html'


class EnrollView(FormView):
    form_class = EnrollForm
    template_name = 'schedule/enroll.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('enroll')


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'schedule/signup.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main')

python/0255 - HyperSchool/task/schedule/templates/schedule/back_to_courses.html
<p><a href="{% url 'main' %}">Go back to the list of courses</a></p>

python/0255 - HyperSchool/task/schedule/templates/schedule/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>HyperSchool</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

python/0255 - HyperSchool/task/schedule/templates/schedule/course_apply.html
<p><a href="{% url 'enroll' %}">Apply to the course {{ course.title }}</a></p>

python/0255 - HyperSchool/task/schedule/templates/schedule/course_details.html
{% extends 'schedule/base.html' %}

{% block content %}

    <h2>{{ course.title }}</h2>

    <p>Information: {{ course.info }}</p>
    <p>Duration: {{ course.duration_months }} months</p>
    <p>Price: {{ course.price }}</p>

    <h3>Teachers:</h3>
    {% for teacher in course.teacher.all %}
        <p><a href="{% url 'teacher_details' teacher.pk %}">{{ teacher.name }} {{ teacher.surname }}</a></p>
    {% endfor %}


    <h3>Students:</h3>
    {% for student in course.student_set.all %}
        <p>{{ student.name }} {{ student.surname }}</p>
    {% endfor %}

    {% include 'schedule/course_apply.html' %}
    {% include 'schedule/back_to_courses.html' %}

{% endblock %}

python/0255 - HyperSchool/task/schedule/templates/schedule/enroll.html
<form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Submit</button>
</form>

python/0255 - HyperSchool/task/schedule/templates/schedule/main.html
{% extends 'schedule/base.html' %}

{% block content %}
    <h2>HyperSchool</h2>
    <p>Hi! Welcome to the site of online HyperSchool!</p>
    <p>Feel free to choose any speciality you are interested in!</p>

    <form method='get'>
        <input type='text' name='q' class='search'>
        <button type='submit'>search</button>
    </form>

    <p>{{ courses.count }} courses</p>

    <ul>
        {% for course in courses %}
            <li><a href="{% url 'course_details' course.pk %}">{{ course.title }}</a></li>
        {% endfor %}
    </ul>


    <p><a href="{% url 'signup' %}">Signup</a></p>
    <p><a href="{% url 'login' %}">Login</a></p>
{% endblock %}

python/0255 - HyperSchool/task/schedule/templates/schedule/signup.html
{% extends 'schedule/base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Sign Up</button>
    </form>
{% endblock %}

python/0255 - HyperSchool/task/schedule/templates/schedule/teacher_details.html
{% extends 'schedule/base.html' %}

{% block content %}

    <h2>{{ course.title }}</h2>

    <p>Name: {{ teacher.name }}</p>
    <p>Surname: {{ teacher.surname }}</p>
    <p>Age: {{ teacher.age }}</p>
    <p>About: {{ teacher.about }}</p>

    {% include 'schedule/back_to_courses.html' %}

{% endblock %}